### ISSUE TITLE
css 渐变文字

### ISSUE THREAD

**Issue by XJIANBIN** [XJIANBIN/XJIANBIN.github.io#50]
### 方法一：借助mask-image属性
[兼容性](https://caniuse.com/#search=mask-image)
```html
<h2 class="text-gradient" data-text="天赐美妞">天赐美妞</h2> 
```
```css
.text-gradient {  
    display: inline-block;
    font-family: '微软雅黑';
    font-size: 10em;
    position: relative; 
}  
  
.text-gradient[data-text]::after {  
    content: attr(data-text);  
    color: green;  
    position: absolute;  
    left: 0;  
    z-index: 2;
    -webkit-mask-image: -webkit-gradient(linear, 0 0, 0 bottom, from(#ff0000), to(rgba(0, 0, 255, 0)));
}
```

###  方法二：background-clip + text-fill-color下的实现
```html
<h2 class="text-gradient">天赐美妞</h2>
```
```css
.text-gradient {  
    display: inline-block;
    font-family: '微软雅黑';
    font-size: 10em;
    position: relative; 
}  
  
.text-gradient[data-text]::after {  
   .text-gradient {  
    display: inline-block;
    color: green;
    font-size: 10em;
    font-family: '微软雅黑';
    background-image: -webkit-gradient(linear, 0 0, 0 bottom, from(rgba(0, 128, 0, 1)), to(rgba(51, 51, 51, 1)));
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
}; 
}
```

### 需要兼容IE 的话，应该就只能是用svg了
svg 需要设置宽高等属性，但是一般文本都是不定长的，只能使用js 动态去设置宽高了。可以使用hack ，弄一个见不到的相同大小的文案，去动态获取高度，然后设置svg 的大小。
```html
<h3>
        <svg xmlns="http://www.w3.org/2000/svg" version="1.1" style="width: 81%; height: 43px;">
        <defs>
          <linearGradient id="grad1" x1="0%" y1="0%" x2="100%" y2="0%">
            <stop offset="0%" style="stop-color: #4fb570; stop-opacity: 1;" />
            <stop offset="25%" style="stop-color: #3da786; stop-opacity: 1;" />
            <stop offset="50%" style="stop-color: #2a989d; stop-opacity: 1;" />
            <stop offset="75%" style="stop-color: #1b8daf; stop-opacity: 1;" />
            <stop offset="100%" style="stop-color: #2c88cc; stop-opacity: 1;" />
          </linearGradient>
        </defs>
        <text x="0" y="40" fill="url(#grad1)" style="font-size: 26px;">
          资源共享
        </text>
      </svg>
    </h3>
```
